version: '3.9'

services:
  service:
    image: laundry-service
    container_name: laundry-service
    ports:
      - "5000:8080"  # http://[::]:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LaundryCleaning;User ID=sa;Password=IY0N@Passw0rd!;TrustServerCertificate=True;
      - SeqSettings__SecretKey=Fhb5CbMGFl9lPJTNbJfyzjAvoPwcl1
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341 # index [0]
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - sqlserver
      - seq
      - rabbitmq
    networks:
      - backend
    restart: on-failure

  scheduler:
    image: laundry-scheduler
    container_name: laundry-scheduler
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LaundryCleaning;User ID=sa;Password=IY0N@Passw0rd!;TrustServerCertificate=True;
      - SeqSettings__SecretKey=Fhb5CbMGFl9lPJTNbJfyzjAvoPwcl1
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341 # index [0]
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - sqlserver
      - seq
      - rabbitmq
    networks:
      - backend
    restart: on-failure
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "IY0N@Passw0rd!"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  seq:
    image: datalust/seq:2024.1
    container_name: seq
    ports:
      - "5341:80"  # default web UI port
      - "5342:5341"  # ingestion API (if needed separately)
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_KEY: "Fhb5CbMGFl9lPJTNbJfyzjAvoPwcl1"
    volumes:
      - seq_data:/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Port AMQP untuk aplikasi
      - "15672:15672"   # Port UI management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  sql_data:
  seq_data:
  rabbitmq_data: